title: Learning
description: >-
  A completely free and open source eLearning platform coded in Jekyll
author: Sarah
locale: British English
keywords: "learning, learninglms, lms, courses, free, learn, hacking, programming"
copyDate: 2020
version: v0.0.1-Beta

baseurl: # URL of the site, i.e: learninglms.gq
pageurl: https://learninglms.gq

markdown: kramdown
highlighter: rouge

twitter:
  site: HermadesCGCO
  author: HermadesCGCO

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

sourceCode: https://github.com/HermadesCGCO/Learning
